squad_client/core/models.py
core: models: add test status totals to TestRun.
=> Add test status totals

Dockerfile, examples/schneider_report.py, examples/schneider_template.html
Add wkhtmltopdf to docker dependencies and update schneider template+script to enable pdf generation, and display tests totals and summary.
=> Schneider test totals

examples/build_report.py, examples/build_report_template.html, squad_client/core/models.py
display all build metadata and default count to ALL in all Squad class
functions
=> reports: improve generic reports

.travis.yml, squad_client/core/api.py, squad_client/manage.py, tests/test_api.py
@mwasilew I guess we can handle credentials this way
=> Manage credentials

squad_client/commands/report.py, squad_client/commands/shell.py, squad_client/commands/submit.py, squad_client/commands/test.py
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
=> WIP: commands: add submit results

requirements-dev.txt, squad_client/core/models.py, tests/fixtures.py
Update squad-client to be in sync with: https://github.com/Linaro/squad/pull/670
=> core: models: update metricthreshold to use env

squad_client/core/models.py, tests/fixtures.py, tests/test_models.py
Close https://github.com/Linaro/squad-client/issues/20
=> core: models: use testrun status endpoint

squad_client/core/models.py, tests/fixtures.py, tests/test_models.py
Fixes https://github.com/Linaro/squad-client/issues/39
=> core: models: add suite do project model

examples/build_report.py, examples/build_report_template.html, squad_client/core/models.py
add metrics attrs and use it in report to call the new metric ep in
Squad.
=> core: models: add metrics

squad_client/core/models.py
This fixes tests that were breaking due to metrics and TestRun status endpoints
=> core: models: fix metrics and testrun status endpoints

README.md
=> Change the attribute from complete to finished

squad_client/core/models.py, tests/fixtures.py, tests/test_models.py
Just filling in a missing option that looked useful to me!
=> Add methods to fetch environments from a project

squad_client/manage.py
This will prevent https://github.com/Linaro/squad-client/pull/47 from breaking
=> manage: avoid configuring api when running tests

examples/build_report.py, examples/build_report_template.html
URLs have changed in SQUAD 1.14 and this patch reflects new URLs
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
=> examples: fix URL in build_report

squad_client/core/api.py, squad_client/core/models.py, squad_client/utils.py, tests/test_models.py
This allows creating projects via squad-client
=> core: models allow project creation

squad_client/commands/create_or_update_project.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/commands/test_create_or_update_project.py, tests/test_shortcuts.py
This PR adds a command that allow users to create or update projects as needed.
=> Add create or update project command

tests/fixtures.py
Fixes https://github.com/Linaro/squad-client/issues/75
=> tests: fixtures: fix fixtures to work along with recent squad changes

squad_client/commands/submit.py, tests/submit_results/sample_results.txt, tests/test_submit.py
The error message was missing the string to include in the format. I added it in and added a test to verify it.
=> Fix a file extension check error message

squad_client/commands/submit.py, tests/data/submit/tuxbuild/build.json, tests/data/submit/tuxbuild/malformed.json, tests/test_submit.py
This will help us add builds as tests to squad
=> Add an option to the submit command that allows the submission of tuxbuild json result files

squad_client/commands/submit.py, tests/data/submit/tuxbuild/buildset.json, tests/data/submit/tuxbuild/empty_kconfig.json, tests/data/submit/tuxbuild/missing_kconfig.json, tests/test_submit.py
=> Do not show the hash for an empty kconfig

squad_client/commands/submit.py, tests/test_submit.py
=> Remove the arch from the test name when using tuxbuild json

squad_client/commands/submit.py, tests/test_submit.py
=> rename redundant _json: tuxbuild_json to tuxbuild only

squad_client/core/models.py
- add missing url attribute
- do not crash in str() method
=> Two fixes for squad models

examples/build_report.py, examples/build_report_template.html
improve load time and shrink report file size
=> examples, build_report: improve load time

squad_client/core/models.py, tests/test_models.py
Fixes https://github.com/Linaro/squad-client/issues/104
=> core: models: cache build tests depending on filters

squad_client/commands/version.py, squad_client/core/api.py, squad_client/manage.py, squad_client/version.py
Fixes https://github.com/Linaro/squad-client/issues/84
=> Check server version

Dockerfile
It reduces the image size from 407MB to 270MB.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
=> Dockerfile: refactor and switch to Alpine based image

squad_client/commands/submit_job.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/data/dummy-definition.yaml, tests/fixtures.py, tests/test_shortcuts.py
This command allow users to submit job requests to Squad via squad-client.
=> commands: submit-job: submit job requests command

squad_client/commands/submit_tuxbuild.py
When adding more than one build at a time, the "download_url" metadata field will vary per build. This fixes that.
=> commands: submit_tuxbuild: use metadata from iterating builds

squad_client/commands/submit_tuxbuild.py
=> submit_tuxbuild: add kconfig as metadata

squad_client/commands/create_or_update_project.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/commands/test_create_or_update_project.py, tests/test_models.py, tests/test_shortcuts.py
models: add the build confidence project attributes
=> Build confidence settings

squad_client/commands/submit_tuxbuild.py, tests/test_submit_tuxbuild.py
Add toolchain to the build metadata
Suggested-by: Naresh Kamboju <naresh.kamboju@linaro.org>
=> commands: submit_tuxbuild: add toolchain to the metadata

squad_client/commands/submit_tuxbuild.py, tests/test_submit_tuxbuild.py
=> commands: submit_tuxbuild: don't add target_arch into the test_name

squad_client/core/models.py
so that we could get all the jobs in the TestJob
object for the build.
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
=> models.py: Support to get jobs for the Build

squad_client/core/api.py
When querying SQUAD the following Traceback was seen:
Traceback (most recent call last):
File "/home/anders/src/squad-client-utils/./squad-stats-report", line 437, in <module>
sys.exit(run())
File "/home/anders/src/squad-client-utils/./squad-stats-report", line 363, in run
devs = get_devices(environments, project.suites(count=ALL), builds)
File "/home/anders/src/squad-client-utils/./squad-stats-report", line 249, in get_devices
for s in testrun.statuses(suite__isnull=False).values():
File "/home/anders/src/squad-client/squad_client/core/models.py", line 717, in statuses
return self.__fetch__(TestRunStatus, filters, count)
File "/home/anders/src/squad-client/squad_client/core/models.py", line 114, in __fetch__
response = SquadApi.get(url, filters)
File …
=> core: api: requests: add retry strategy
