Linaro/squad-client

setup.py
This changes `squad-client-manage` program name to `squad-client` only. It reads better.
PS: suggested by @danrue
=> setup.py: make squad-client program name shorter

README.md, examples/example_report.py
Some of the docs and examples have incorrect import paths (missing `core`).
Fixes #24 .
=> Fix the import paths for some docs and examples

squad_client/manage.py
It was already mandatory, but only in command line, now it checks if env variable is set as well.
=> manage: make squad-host mandatory in environment

.gitignore, requirements.txt, squad_client/manage.py
Fixes https://github.com/Linaro/squad-client/issues/4
This uses `requests_cache`, a small caching library that will blindly cache contens coming from requests library.
Running a simple test case
```bash
./manage.py shell examples/build_report.py --script-params "--squad-host http://localhost:8000 --group lkft --project linux-stable-rc-4.14-oe --build v4.14.74 --token $SQUAD_TOKEN --template examples/build_report_template.html --output generated.html"
```
I got 690 requests without caching and 484 with cache on
=> manage: add basic caching

examples/build_report.py
By default max of 50 suites were retrieved. This leads to errors if the
tests from the build were included in the suite that is further down the
list. This patch retrieves all suites belonging to the project and fixes
the issue.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
=> examples: fix suite retrieval in build_report.py

squad_client/commands/submit.py
Add more explanation to the format of --test-name parameter
Fixes: #67
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
=> commands: fix submit command docs

squad_client/core/models.py, squad_client/shortcuts.py, tests/test_models.py
Now one can get all tests belonging to a Suite. Although that's probably a huge test set, it shouldn't time out the backend server.
It won't timeout backend after https://github.com/Linaro/squad/pull/745 is merged and rolled out
=> core: models: query tests in Suite class

tests/__init__.py
Verbose (`--verbose`) does not appear to work when running tests for a specific module.
example:
```
./manage.py --debug --squad-host http://localhost:9000 test -v tests.test_submit
[INFO] Running tests
[INFO] Starting a fresh squad instance on port 9000
[INFO] Creating database schema
[INFO] Applying tests/fixtures.py
..........
----------------------------------------------------------------------
Ran 10 tests in 19.093s
OK
[INFO] Terminating daemons
```
With this PR applied, verbose will work (ignore the failures, thats from some other changes):
```
./manage.py --squad-host http://localhost:9000 test -v tests.test_submit
[INFO] Running tests
[INFO] Starting a fresh squad instance on port 9000
[INFO] Creating database schema
[INFO] Applying tests/fixtures.py
test_submit …
```
=> Allow the verbose flag to be used when running specific tests

squad_client/core/models.py, tests/fixtures.py, tests/test_models.py
This will alow fetching tests directly from the build endpoint, making a way around testrun
=> core: models: add tests endpoint to build

examples/build_report.py
Since Squad api changed displaying full url
rather than id for related objects for a SQUAD object
eg. ('suite' shows url when viewing a test) this has broken
referencing items in the return dicts in the report. This fixes
that
=> examples, build report: fix objects keys

.flake8, .gitignore, requirements.txt, squad_client/commands/submit.py, squad_client/commands/submit_tuxbuild.py, tests/data/submit/tuxbuild/empty_build_status.json, tests/data/submit/tuxbuild/malformed_build_status.json, tests/data/submit/tuxbuild/malformed_kconfig.json, tests/data/submit/tuxbuild/missing_build_status.json, tests/test_submit.py, tests/test_submit_tuxbuild.py
A little bigger than I first imagined, but I think we've got a good amount of work done here.
- Add a new command: `submit-tuxbuild`
- Remove `tuxbuild` details from the submit command.
- Move `tuxbuild` tests to their own file.
- Verify `tuxbuild` data using the `jsonschema` library.
- Add the `jsonschema` library to the requirements file.
- Add additional test cases and test data specific to `tuxbuild` usage.
- Ignore the `.venv` directory in both `git` and `flake8`
What was not done yet, that will be done at a later time:
- Attachments
- Logs
- Metadata
Feel free to leave lots of comments on how things can be improved. Thanks!
=> Add a new command for submitting tuxbuild data to squad

squad_client/commands/submit_tuxbuild.py, tests/data/submit/tuxbuild/build.json, tests/test_submit_tuxbuild.py
It'll prevent things like this from happening: https://qa-reports.linaro.org/lkft/linux-stable-rc-linux-4.14.y/build/v4/?failures_only=false&results_layout=envbox#!#test-results
=> commands: submit_tuxbuild: fix key in case of builds with dotted version

squad_client/commands/create_or_update_project.py, squad_client/commands/report.py, squad_client/commands/shell.py, squad_client/commands/submit.py, squad_client/commands/submit_tuxbuild.py, squad_client/commands/test.py, squad_client/core/api.py, squad_client/core/models.py, squad_client/manage.py, squad_client/report.py
In general it is a good practice to use the module name for the logger
such that it can be controlled within the python logging configuration
without modifying other loggers.
Right now, without this change, you have to change the root logger
configuration, which could impact other libraries or scripts.
=> squad_client: use module name for the logger name

squad_client/core/api.py, squad_client/manage.py
This way libs that use squad-client can turn it on/off without having to use squad-client as a CLI
=> core: api: configure cache in SquadApi.configure()

Dockerfile
alpine does not include bash by default (only sh).
bash is required for our pipeline usage of squad-client, so this would
be nice to include.
=> dockerfile: add bash

squad_client/commands/submit_tuxbuild.py
Since we do not pin the version of jsonschema, an upstream change has
caused a problem with the pipeline.
jsonschema recently changed their default schema version to something
newer that is not compatiable with what we have defined in squad-client.
This sets the schema version to what it should be so that we can
investigate changing to the newer schema at a later date.
=> submit_tuxbuild: set schema version

squad_client/commands/create_or_update_project.py, squad_client/core/models.py, squad_client/shortcuts.py, squad_client/version.py, tests/commands/test_create_or_update_project.py, tests/fixtures.py, tests/test_models.py
This PR adds a new arg in `create-or-update-project` called `--thresholds` that makes sure required thresholds are in place.
The PR also fixes tests regarding the latest changes in SQUAD's MetricThreshold object.
=> Enable metric threshold

Dockerfile
This was removed in the latest alpine release, so we are removing it
from the container for now.
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.15.0#Significant_removals
Fixes #134
=> dockerfile: remove wkhtmltopdf

squad_client/commands/submit_tuxbuild.py
Add a config field that points to tuxsuite's generated config artifact.
Shouldn't be needed to store the 'config' file since the tuxsuite url
are stored for 90 days, which should be enough time to report a
regression.
=> submit_tuxbuild: add config file url to the metadata

squad_client/commands/submit.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/fixtures.py, tests/test_models.py
Treat the testrun metadata like a squadobject, and use the built-in
features to send and recieve it.
Originally this was treated like a dictionary, and so there are some
changes related to that.
Because the testrun metadata does not really use an id, we remove the
uuid when we encode it to json.
=> all: fetch testrun metadata from squad

squad_client/commands/create_or_update_project.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/test_shortcuts.py
Add the flag to force finishing builds on timeout to squad-client. Also add that to the `create-or-update-project` command
=> core: models: add field for forcing builds finishing on timeout

squad_client/commands/submit_tuxbuild.py, tests/data/submit/tuxbuild/build.json, tests/data/submit/tuxbuild/buildset.json, tests/test_submit_tuxbuild.py
Drop names that have been made up, use the names that tuxsuite provides
for us. Use 'git_sha' instead of 'git_commit', 'git_ref' instead of
'git_branch' and use 'kernel_version' instead of
'make_kernelversion'.
=> commands: submit_tuxbuild: drop duplicate names

squad_client/core/models.py, tests/test_models.py
[core: models: fix initialization of class variables](https://github.com/Linaro/squad-client/pull/155/commits/217d59a282e23df16836a0c6b6ef5f54ee4976c2) 
Initialize class variables with None and then set them to a mutable type
when the instance calls a method.
If you initialize a class variable with a mutable type, it will be
shared amonst all instances of the class, rather than being instance
specific.
This means a change to that variable in one instance will affect all
other instances.
https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables
"The concept of class-variable and instance-variable is fine till the
point where you use mutable objects".
Suggested-by: Charles Oliveira <charles.oliveira@linaro.org>
=> Class variables should not be mutable

squad_client/commands/submit_tuxsuite.py, squad_client/core/api.py, squad_client/core/models.py, squad_client/shortcuts.py, squad_client/version.py, tests/commands/test_submit_tuxsuite.py, tests/data/sample_tuxsuite_builds.json, tests/data/sample_tuxsuite_tests.json, tests/data/sample_tuxsuite_tuxplan.json, tests/fixtures.py, tests/test_shortcuts.py
This subcommand adds support for integrating TuxSuite and SQUAD. It should be used as:
```bash
$ squad-client submit-tuxsuite \
--group lkft \
--project linux-stable-rc-linux-5.12.y \
--build v5.12.19 \
--backend tuxsuite.com \
--json results-from-tuxsuite-cli.json
```
The outcome of this command is subsequent calls to SQUAD's `/api/watchjob` endpoint, triggering the TuxSuite backend, fetching both build and results from Tux.
=> Add submit TuxSuite command

.github/workflows/test.yml, squad_client/commands/download_results.py, squad_client/core/api.py, squad_client/shortcuts.py, tests/test_shortcuts.py
```bash
$ export SQUAD_HOST=https://qa-reports.linaro.org/
$ export SQUAD_TOKEN=<token>
$ ./manage.py \
download-results \
--group "lkft" \
--project "linux-stable-rc-linux-5.19.y" \
--build v5.19.4
[INFO] Downloading test results for lkft/linux-stable-rc-linux-5.19.y/v5.19.4/(all envs)/(all suites) to v5.19.4.txt
$ time ./manage.py \
download-results \
--group "lkft" \
--project "linux-stable-rc-linux-5.19.y" \
--build v5.19.3
[INFO] Downloading test results for lkft/linux-stable-rc-linux-5.19.y/v5.19.3/(all envs)/(all suites) to v5.19.3.txt
real	2m16.585s
user	0m4.447s
sys	0m0.187s
$ diff -u v5.19.3.txt v5.19.4.txt > diff.txt
```
Files [v5.19.3.txt](https://github.com/Linaro/squad-client/files/9434773/v5.19.3.txt) and [v5.19.4.txt](https://github.com/Linaro/squad-client/files/9434777/v5. …
=> commands: download_results: add command to download test results

squad_client/core/models.py
so that we could get the job duration with them
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
=> models.py: add started_at ended_at for TestJob

squad_client/shortcuts.py
Make it possible to pass a date like next-20221220 as a build, and get_build() wont think its the build 'next' minus '20221220' builds.
Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
Suggested-by: Charles Oliveria <charles.oliveria@linaro.org>
=> squad_client: shortcuts: fix regex

squad_client/core/models.py, tests/fixtures.py, tests/test_models.py
Add a property `attachement_urls` to TestRuns that returns the download URLs for a given TestRun.
=> squad_client/core/models.py: Add attachment_urls property to TestRuns

squad_client/core/models.py, tests/test_models.py
This will be used to help handling testrun attachments. It wraps the feature of downloading it inside a `read` function.
=> core/models.py: add TestRunAttachment class

squad_client/core/models.py
The feature that allows a TestRun ID to be passed to the TestRun constructor was accidentally removed during a recent update (https://github.com/Linaro/squad-client/pull/171)
As a result, the TestRun init function was missing option to initialise a TestRun object by an existing TestRun ID.
Add ID as an optional parameter to the TestRun init function to restore this functionality.
Move the `super().__init__(_id)` so it is called after the default values of the object's members have been initialised to None or empty. This means that the data will be filled in if an ID is provided and initialised to None or [] if no ID is provided.
=> squad_client/core/models: Fix TestRun init function

squad_client/commands/download_attachments.py, squad_client/commands/submit.py, squad_client/core/models.py, squad_client/shortcuts.py, tests/test_shortcuts.py
Add support for attachment downloads from squad-client CLI.
Depends on fix for TestRun object init function: https://github.com/Linaro/squad-client/pull/172
=> Add attachment download command to squad-client

tests/test_shortcuts.py
Since submit_results now returns two values (success and testrun ID), the test_basic for submit_results needs to be updated to reflect this, otherwise the assertion will always return True.
=> tests/test_shortcuts: Fix check for success on submit_results return
